export { default as Hero } from "./Hero";
export { default as Navbar } from "./Navbar";
export { default as Menu } from "./Menu";
export { default as NewProducts } from "./NewProducts";
export { default as Loader } from "./Loader";
export { default as ErrorMessage } from "./ErrorMessage";
export { default as Newsletter } from "./Newsletter";
export { default as Collections } from "./Collections";
export { default as Footer } from "./Footer";
